paths:
  data: src/data
  static: public
  uploads: public/images
collections_config:
  pages:
    path: src/content/pages
    url: '/[slug]/'
    output: true
    icon: wysiwyg
    _enabled_editors:
      - visual
  data:
    path: src/data
    disable_add: true
    disable_add_folder: true
_enabled_editors:
  - visual
  - content
_inputs:
  grid_size:
    options:
      hidden: shop_page
  content_blocks:
    options:
      hidden: '!shop_page'
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
timezone: Etc/UTC
