paths:
  data: src/data
  static: public
  uploads: public/images
collections_config:
  pages:
    path: src/content/pages
    url: "/[slug]/"
    output: true
    icon: wysiwyg
    _enabled_editors:
      - visual
_enabled_editors:
  - visual
  - content
_inputs: {}
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
timezone: Etc/UTC
