source: src
output: dist
paths:
  uploads: uploads
collections_config:
  pages:
    path: content/pages
    output: true
    icon: notes
    _editables: {}
    _inputs: {}
    _select_data: {}
    _structures: {}
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas: {}
_enabled_editors:
  - visual
_inputs: {}
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
timezone: Etc/UTC
